name = TaskManager
description = A simple layout with header, content and footer regions
preview = preview.png
template = taskmanager-layout

; Regions
# regions[branding]       = Branding
regions[header]         = Header
# regions[navigation]     = Navigation bar
# regions[highlighted]    = Highlighted
# regions[help]           = Help
regions[content]        = Content
# regions[sidebar_first]  = First sidebar
# regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/taskmanager/taskmanager.layout.css
