name = TaskManager
description = A simple layout with header, content and footer regions
preview = preview.png
template = taskmanager-layout

; ========================================
; Regions
; ========================================
regions[menu] = Menu
regions[column01] = First Column
regions[column02] = Second Column
regions[column03] = Third Column
regions[sidebar] = Sidebar

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/layouts/taskmanager/taskmanager.layout.css
stylesheets[all][] = css/layouts/taskmanager/taskmanager.style.css